import re


def clean_sql(query: str) -> str:
    """
    Standardized utility for cleaning SQL generated by LLMs.
    Strips out markdown code blocks and trailing semicolons.
    """
    if not query:
        return ""

    cleaned = query.strip()
    
    # Check for fenced SQL block anywhere in the string
    match = re.search(r"```(?:sql)?\s*(.*?)\s*```", cleaned, re.IGNORECASE | re.DOTALL)
    if match:
        cleaned = match.group(1).strip()
    else:
        cleaned = re.sub(r"^```(?:sql)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)

    # Strip trailing semicolon if present
    cleaned = cleaned.strip()
    if cleaned.endswith(";"):
        cleaned = cleaned[:-1].strip()

    return cleaned
