import re


def clean_sql(query: str) -> str:
    """
    Standardized utility for cleaning SQL generated by LLMs.
    Strips out markdown code blocks and trailing semicolons.
    """
    if not query:
        return ""

    cleaned = query.strip()
    
    # Check for fenced SQL block anywhere in the string
    match = re.search(r"```(?:sql)?\s*(.*?)\s*```", cleaned, re.IGNORECASE | re.DOTALL)
    if match:
        cleaned = match.group(1).strip()
    else:
        cleaned = re.sub(r"^```(?:sql)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)

    # Strip trailing semicolon if present
    cleaned = cleaned.strip()
    if cleaned.endswith(";"):
        cleaned = cleaned[:-1].strip()

    return cleaned


def replace_unquoted_char(sql: str, old: str, new: str) -> str:
    """
    Replaces occurrences of `old` with `new` ONLY outside of single-quoted string literals.
    Handles escaped quotes (which in SQL are `''`) naturally because splitting on `'` 
    keeps odd/even parity correct.
    """
    if not sql:
        return sql
        
    parts = sql.split("'")
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace(old, new)
    return "'".join(parts)


def resolve_wkt_polygons(sql: str, locations_dict: dict | None) -> str:
    """Replaces `@<name>_wkt@` placeholders in SQL with full WKT string literals for database execution."""
    if not sql or not locations_dict or "coords" not in locations_dict:
        return sql
    
    final_sql = sql
    for placeholder, wkt_str in locations_dict["coords"].items():
        clean_wkt = wkt_str.strip("'")
        replacement = f"'{clean_wkt}'"
        final_sql = re.sub(r"['\"]?@" + re.escape(placeholder) + r"@['\"]?", replacement, final_sql)
        
    return final_sql


