import re

def clean_sql(query: str) -> str:
    """
    Standardized utility for cleaning SQL generated by LLMs.
    Strips out markdown code blocks and trailing semicolons.
    """
    if not query:
        return ""
    
    # Remove markdown code fences if present
    cleaned = re.sub(r"^```sql\s*", "", query, flags=re.IGNORECASE)
    cleaned = re.sub(r"^```\s*", "", cleaned)
    cleaned = re.sub(r"```$", "", cleaned.strip())
    
    # Strip trailing semicolon if present
    cleaned = cleaned.strip()
    if cleaned.endswith(";"):
        cleaned = cleaned[:-1].strip()
        
    return cleaned
