"""
enrichment_models.py - Professional and strict data models for Category Enrichment.

Defines schemas representing extracted filters, LLM transformation plans, 
and database metadata structures.
"""

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

class SQLFilterParams(BaseModel):
    """
    Represents a single filter condition extracted from the WHERE clause.
    """
    source_table: str = Field(
        description="The resolved canonical table name (e.g., catalog.schema.table) the column belongs to."
    )
    source_column: str = Field(
        description="The resolved name of the database column being filtered."
    )
    operator: str = Field(
        description="The SQL comparison operator of the predicate (e.g., '=', 'LIKE', 'IN', 'IS NULL', 'BETWEEN')."
    )
    value: Any = Field(
        None, 
        description="The raw comparison value(s). Can be a primitive (str, int, float) or list/tuple of primitives."
    )
    original_expression: str = Field(
        description="The raw Trino SQL representation of the matched leaf comparison expression."
    )
    is_unnest: bool = Field(
        default=False, 
        description="True if this column was unnested from an array column using Trino UNNEST syntax."
    )
    is_negated: bool = Field(
        default=False,
        description="True if this filter predicate is wrapped in an odd number of NOT operators."
    )
    match_type: Literal["exact", "prefix", "suffix", "substring", "in_list", "null", "range", "inequality"] = Field(
        description="Categorization of the query's match filter behavior."
    )


class FilterTransformation(BaseModel):
    """
    Represents the mapping decision for a single column-value filter pair.
    """
    column: str = Field(
        description="The target column name of the filter condition."
    )
    table: str = Field(
        description="The resolved canonical table name the column belongs to, propagated from the extraction phase."
    )
    original_value: str = Field(
        description="The original user-supplied filter value string (e.g. '%italian%')."
    )
    old_operator: str = Field(
        description="The original SQL comparison operator (e.g., '=', 'LIKE', 'IN')."
    )
    new_operator: str = Field(
        description="The target SQL comparison operator (e.g., '=', 'IN')."
    )
    refined_values: List[str] = Field(
        description="The list of canonical candidate strings to replace the original filter value."
    )
    changed_filter: bool = Field(
        description="Indicates whether this filter mapping should be programmatically applied to the SQL AST."
    )
    reasoning: str = Field(
        description="Explanation of the choice (e.g. Keep, Replace, Omit) and semantic eligibility criteria."
    )


class TransformationPlan(BaseModel):
    """
    The structured plan containing list of filter mapping actions generated by LLM.
    """
    enrichment_details: List[FilterTransformation] = Field(
        default_factory=list,
        description="The collection of proposed predicate transformations."
    )


class AgentSQLTable(BaseModel):
    """
    Metadata representation of database tables and columns provided to the pipeline.
    """
    name: str = Field(
        description="The table's fully qualified name."
    )
    description: str = Field(
        default="",
        description="A summary of the table's contents and schema role."
    )
    columns: Dict[str, Any] = Field(
        default_factory=dict,
        description="A dictionary mapping column names to metadata dicts (e.g. {'column_type': 'large_category'})."
    )
