export const FLAG_CATEGORIES: Record<string, string[]> = {
  Extraction: [
    'EXTRACTOR_MODEL',
    'EXTRACTOR_TEMPERATURE',
    'EXTRACTOR_TOP_K_TABLES',
    'DEFAULT_TABLE_SCOPING_MODE',
  ],
  'Schema Explorer': [
    'MAX_PROFILES_TO_FETCH',
    'PROFILE_FETCH_CONCURRENCY',
    'SCHEMA_CACHE_TTL',
    'PROFILE_CACHE_TTL',
    'SCHEMA_SEMANTIC_TYPING',
    'SCHEMA_JOIN_GRAPH',
    'SCHEMA_SUMMARIZATION',
    'SCHEMA_AMBIGUITY_DETECT',
    'SCHEMA_EXPLORER_MODEL',
    'SCHEMA_TOP_K_JOINS',
  ],
  'Query Builder': ['QUERY_BUILDER_MODEL', 'QUERY_BUILDER_TEMPERATURE'],
  Refiner: [
    'MAX_REFINER_ITERATIONS',
    'MAX_SCHEMA_REPLAN_ITERATIONS',
    'REFINER_SCHEMA_CONTEXT_TABLES',
    'REFINER_MODEL',
  ],
  'Satisfaction Check': [
    'SATISFACTION_CHECK_ENABLED',
    'SATISFACTION_CHECK_EXECUTION',
    'SATISFACTION_CHECK_PLAUSIBILITY',
    'SATISFACTION_CHECK_COLUMNS',
    'SATISFACTION_CHECK_SEMANTIC',
    'SATISFACTION_MIN_ROWS',
    'SATISFACTION_MAX_ROWS',
    'SATISFACTION_SEMANTIC_THRESHOLD',
    'SATISFACTION_JUDGE_MODEL',
  ],
  Skills: ['SKILLS_ENABLED', 'SKILLS_HOT_RELOAD', 'SKILLS_CACHE_TTL'],
  Evaluation: ['LLM_JUDGE_ENABLED', 'EVAL_PARALLEL_WORKERS', 'EVAL_JUDGE_MODEL'],
  'Catalog Validation': ['CATALOG_VALIDATION_ENABLED', 'CATALOG_CACHE_TTL'],
};

export const TYPE_COLORS: Record<string, string> = {
  bool: 'blue',
  int: 'green',
  float: 'cyan',
  string: 'purple',
  json: 'orange',
};
