"""Initial schema

Revision ID: 01333a305f59
Revises: 
Create Date: 2026-05-07 22:03:49.183276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01333a305f59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_schedules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_scope', sa.JSON(), nullable=True),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_schedules_dataset_id'), 'evaluation_schedules', ['dataset_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sandbox', 'verified', 'production', 'degraded', name='tablestatus'), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oasis_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openmetadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_name'), 'tables', ['name'], unique=False)
    op.create_table('user_scopes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scopes_user_id'), 'user_scopes', ['user_id'], unique=False)
    op.create_table('audit_queries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tables_accessed', sa.JSON(), nullable=True),
    sa.Column('final_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_row_count', sa.Integer(), nullable=True),
    sa.Column('result_columns', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('refiner_iterations', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('langfuse_trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('explanation_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_queries_table_id'), 'audit_queries', ['table_id'], unique=False)
    op.create_table('cross_table_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('join_suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_strength', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('common_columns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['target_table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_table_profiles_source_table_id'), 'cross_table_profiles', ['source_table_id'], unique=False)
    op.create_table('enrichment_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_versions_table_id'), 'enrichment_versions', ['table_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('fail_rate', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='evalstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_breakdown', sa.JSON(), nullable=True),
    sa.Column('dimension_averages', sa.JSON(), nullable=True),
    sa.Column('regression_detected', sa.Boolean(), nullable=False),
    sa.Column('regression_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_dataset_id'), 'eval_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_table_id'), 'eval_runs', ['table_id'], unique=False)
    op.create_table('evaluation_alerts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_alerts_run_id'), 'evaluation_alerts', ['run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_alerts_table_id'), 'evaluation_alerts', ['table_id'], unique=False)
    op.create_table('golden_questions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Enum('simple', 'medium', 'complex', name='difficultylevel'), nullable=False),
    sa.Column('question_type', sa.Enum('simple', 'complex', 'join', 'geo', 'aggregate', 'time_series', name='questiontype'), nullable=False),
    sa.Column('coverage_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_questions_table_id'), 'golden_questions', ['table_id'], unique=False)
    op.create_table('table_health',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('health_status', sa.Enum('good', 'warning', 'critical', name='healthstatus'), nullable=False),
    sa.Column('eval_success_rate', sa.Float(), nullable=True),
    sa.Column('feedback_ratio', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('schema_drift_flag', sa.Boolean(), nullable=False),
    sa.Column('failure_wrong_table', sa.Integer(), nullable=False),
    sa.Column('failure_wrong_sql', sa.Integer(), nullable=False),
    sa.Column('failure_empty_result', sa.Integer(), nullable=False),
    sa.Column('failure_execution_error', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_health_table_id'), 'table_health', ['table_id'], unique=True)
    op.create_table('table_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='profilingstatus'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('null_rate_avg', sa.Float(), nullable=True),
    sa.Column('duplicate_rate', sa.Float(), nullable=True),
    sa.Column('sample_data', sa.JSON(), nullable=True),
    sa.Column('auto_insights', sa.JSON(), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('cached_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_profiles_table_id'), 'table_profiles', ['table_id'], unique=False)
    op.create_table('column_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('column_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('null_count', sa.Integer(), nullable=True),
    sa.Column('null_rate', sa.Float(), nullable=True),
    sa.Column('distinct_count', sa.Integer(), nullable=True),
    sa.Column('min_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('median_value', sa.Float(), nullable=True),
    sa.Column('top_values', sa.JSON(), nullable=True),
    sa.Column('is_categorical', sa.Boolean(), nullable=False),
    sa.Column('is_geo', sa.Boolean(), nullable=False),
    sa.Column('is_time', sa.Boolean(), nullable=False),
    sa.Column('semantic_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['table_profiles.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_profiles_profile_id'), 'column_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_column_profiles_table_id'), 'column_profiles', ['table_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['golden_questions.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_run_id'), 'eval_results', ['run_id'], unique=False)
    op.create_table('evaluation_history_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_history_metrics_run_id'), 'evaluation_history_metrics', ['run_id'], unique=False)
    op.create_table('query_feedback',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Enum('positive', 'negative', name='feedbackrating'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggested_correction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['audit_queries.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_feedback_query_id'), 'query_feedback', ['query_id'], unique=False)
    op.create_index(op.f('ix_query_feedback_table_id'), 'query_feedback', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_feedback_table_id'), table_name='query_feedback')
    op.drop_index(op.f('ix_query_feedback_query_id'), table_name='query_feedback')
    op.drop_table('query_feedback')
    op.drop_index(op.f('ix_evaluation_history_metrics_run_id'), table_name='evaluation_history_metrics')
    op.drop_table('evaluation_history_metrics')
    op.drop_index(op.f('ix_eval_results_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_column_profiles_table_id'), table_name='column_profiles')
    op.drop_index(op.f('ix_column_profiles_profile_id'), table_name='column_profiles')
    op.drop_table('column_profiles')
    op.drop_index(op.f('ix_table_profiles_table_id'), table_name='table_profiles')
    op.drop_table('table_profiles')
    op.drop_index(op.f('ix_table_health_table_id'), table_name='table_health')
    op.drop_table('table_health')
    op.drop_index(op.f('ix_golden_questions_table_id'), table_name='golden_questions')
    op.drop_table('golden_questions')
    op.drop_index(op.f('ix_evaluation_alerts_table_id'), table_name='evaluation_alerts')
    op.drop_index(op.f('ix_evaluation_alerts_run_id'), table_name='evaluation_alerts')
    op.drop_table('evaluation_alerts')
    op.drop_index(op.f('ix_eval_runs_table_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_dataset_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_enrichment_versions_table_id'), table_name='enrichment_versions')
    op.drop_table('enrichment_versions')
    op.drop_index(op.f('ix_cross_table_profiles_source_table_id'), table_name='cross_table_profiles')
    op.drop_table('cross_table_profiles')
    op.drop_index(op.f('ix_audit_queries_table_id'), table_name='audit_queries')
    op.drop_table('audit_queries')
    op.drop_index(op.f('ix_user_scopes_user_id'), table_name='user_scopes')
    op.drop_table('user_scopes')
    op.drop_index(op.f('ix_tables_name'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_evaluation_schedules_dataset_id'), table_name='evaluation_schedules')
    op.drop_table('evaluation_schedules')
    # ### end Alembic commands ###
