"""Split profiling tables

Revision ID: 5da5e154c87c
Revises: a123e456b789
Create Date: 2026-07-20 11:42:20.151926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5da5e154c87c'
down_revision: Union[str, None] = 'a123e456b789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'canceled' to the enum
    op.execute("ALTER TYPE profilingstatus ADD VALUE IF NOT EXISTS 'canceled'")

    op.create_table('profiling_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'canceled', name='profilingstatus', create_type=False), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiling_runs_table_id'), 'profiling_runs', ['table_id'], unique=False)

    op.drop_column('table_profiles', 'is_partial')
    op.drop_column('table_profiles', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_profiles', sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'canceled', name='profilingstatus'), autoincrement=False, nullable=True))
    op.add_column('table_profiles', sa.Column('is_partial', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_profiling_runs_table_id'), table_name='profiling_runs')
    op.drop_table('profiling_runs')
    # ### end Alembic commands ###
