"""Add unique constraint to tables

Revision ID: 70e8a34ff877
Revises: f9a3d1c8e205
Create Date: 2026-07-07 11:17:43.459879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70e8a34ff877'
down_revision: Union[str, None] = 'f9a3d1c8e205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_table_profiles_table_id', 'table_profiles', type_='unique')
    op.drop_index('ix_table_profiles_table_id', table_name='table_profiles')
    op.create_index(op.f('ix_table_profiles_table_id'), 'table_profiles', ['table_id'], unique=True)
    op.drop_column('table_profiles', 'is_partial')
    op.create_unique_constraint('uq_table_fqn', 'tables', ['catalog', 'schema_name', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_table_fqn', 'tables', type_='unique')
    op.add_column('table_profiles', sa.Column('is_partial', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_table_profiles_table_id'), table_name='table_profiles')
    op.create_index('ix_table_profiles_table_id', 'table_profiles', ['table_id'], unique=False)
    op.create_unique_constraint('uq_table_profiles_table_id', 'table_profiles', ['table_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
