"""Add status to HttpExtractor

Revision ID: aeb0e2695517
Revises: 781457ead87d
Create Date: 2026-06-08 13:10:35.703108

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aeb0e2695517'
down_revision: str | None = '781457ead87d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE extractorstatus AS ENUM ('draft', 'sandbox', 'verified', 'production', 'degraded')")
    op.add_column('http_extractors', sa.Column('status', postgresql.ENUM('draft', 'sandbox', 'verified', 'production', 'degraded', name='extractorstatus', create_type=False), server_default='draft', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('http_extractors', 'status')
    op.execute("DROP TYPE extractorstatus")
    # ### end Alembic commands ###
