"""Add ForeignKeyMapping

Revision ID: d35412e44b34
Revises: c3f1a9e72b84
Create Date: 2026-05-28 14:45:19.603727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd35412e44b34'
down_revision: Union[str, None] = 'c3f1a9e72b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_key_mappings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_column', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_column', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_table_id'], ['tables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_key_mappings_table_id'), 'foreign_key_mappings', ['table_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_promotion_run_id'), 'eval_runs', ['promotion_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_runs_promotion_run_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_foreign_key_mappings_table_id'), table_name='foreign_key_mappings')
    op.drop_table('foreign_key_mappings')
    # ### end Alembic commands ###
