"""remove auto_insights from TableProfile

Revision ID: d3d006362f40
Revises: 5da5e154c87c
Create Date: 2026-07-21 07:41:31.472388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d006362f40'
down_revision: Union[str, None] = '5da5e154c87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_profiles', 'auto_insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_profiles', sa.Column('auto_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
