"""Add Organization and SSO fields

Revision ID: f4d69a17d156
Revises: d35412e44b34
Create Date: 2026-06-09 14:35:40.420571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4d69a17d156'
down_revision: Union[str, None] = 'd35412e44b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_organizations_name'), 'organizations', ['name'], unique=True, schema='security')
    op.add_column('users', sa.Column('sso_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='security')
    op.add_column('users', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='security')
    op.create_index(op.f('ix_security_users_sso_id'), 'users', ['sso_id'], unique=False, schema='security')
    op.create_table('organization_members',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['security.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['security.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id'),
    schema='security'
    )
    op.drop_index('ix_http_extractors_name', table_name='http_extractors')
    op.drop_table('http_extractors')
    op.drop_index('ix_admins_username', table_name='admins')
    op.drop_table('admins')
    op.drop_column('tables', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_table('admins',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    op.create_index('ix_admins_username', 'admins', ['username'], unique=True)
    op.create_table('http_extractors',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'sandbox', 'verified', 'production', 'degraded', name='extractorstatus'), server_default=sa.text("'draft'::extractorstatus"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='http_extractors_pkey')
    )
    op.create_index('ix_http_extractors_name', 'http_extractors', ['name'], unique=True)
    op.drop_table('organization_members', schema='security')
    op.drop_column('users', 'provider', schema='security')
    op.drop_column('users', 'sso_id', schema='security')
    op.drop_index(op.f('ix_security_organizations_name'), table_name='organizations', schema='security')
    op.drop_table('organizations', schema='security')
    # ### end Alembic commands ###
