"""Add Organization and SSO fields

Revision ID: f4d69a17d156
Revises: aeb0e2695517
Create Date: 2026-06-09 14:35:40.420571

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4d69a17d156'
down_revision: str | None = 'aeb0e2695517'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_organizations_name'), 'organizations', ['name'], unique=True, schema='security')
    op.add_column('users', sa.Column('sso_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='security')
    op.add_column('users', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='security')
    op.create_index(op.f('ix_security_users_sso_id'), 'users', ['sso_id'], unique=False, schema='security')
    op.create_table('organization_members',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['security.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['security.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id'),
    schema='security'
    )

    # Conditional drops to handle clean DB sequence vs dirty state safely
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'admins' in tables:
        indexes = [i['name'] for i in inspector.get_indexes('admins')]
        if 'ix_admins_username' in indexes:
            op.drop_index('ix_admins_username', table_name='admins')
        op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'admins' not in tables:
        op.create_table('admins',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='admins_pkey')
        )
        op.create_index('ix_admins_username', 'admins', ['username'], unique=True)

    # Clean security tables
    security_tables = inspector.get_table_names(schema='security')
    if 'organization_members' in security_tables:
        op.drop_table('organization_members', schema='security')

    if 'users' in security_tables:
        columns_users = [c['name'] for c in inspector.get_columns('users', schema='security')]
        if 'provider' in columns_users:
            op.drop_column('users', 'provider', schema='security')
        if 'sso_id' in columns_users:
            indexes_users = [i['name'] for i in inspector.get_indexes('users', schema='security')]
            if 'ix_security_users_sso_id' in indexes_users:
                op.drop_index(op.f('ix_security_users_sso_id'), table_name='users', schema='security')
            op.drop_column('users', 'sso_id', schema='security')

    if 'organizations' in security_tables:
        indexes_org = [i['name'] for i in inspector.get_indexes('organizations', schema='security')]
        if 'ix_security_organizations_name' in indexes_org:
            op.drop_index(op.f('ix_security_organizations_name'), table_name='organizations', schema='security')
        op.drop_table('organizations', schema='security')
    # ### end Alembic commands ###
