connector.name=snowflake
connection-url=jdbc:snowflake://RSRSBDK-YDB67606.snowflakecomputing.com
connection-user=BARVAZ_HAMOOD
connection-password=${ENV:SNOWFLAKE_PASSWORD}
snowflake.account=RSRSBDK-YDB67606
snowflake.role=PARTICIPANT
snowflake.warehouse=COMPUTE_WH_PARTICIPANT
snowflake.database=AIRLINES
